------------------
```markdown
# Copyright © 2024 Meysam Goodarzi
This notebook is licensed under CC BY-NC 4.0 with the following amandments:
- Individuals may use, share, and adapt this material for non-commercial purposes with attribution.
- Institutions/Companies must obtain written consent to use this material, except for nonprofits.
- Commercial use is prohibited without permission.  
Contact: analytica@meysam-goodarzi.com
```
------------------------------
❗❗❗ **IMPORTANT**❗❗❗ **Create a copy of this notebook**

In order to work with this Google Colab you need to create a copy of it. Please **DO NOT** provide your answers here. Instead, work on the copy version. To make a copy:

**Click on: File -> save a copy in drive**

Have you successfully created the copy? if yes, there must be a new tab opened in your browser. Now move to the copy and start from there!

----------------------------------------------

# Introduction to Pandas

This notebook will cover essential topics to get started with Pandas. We will explore various Pandas functions and compare some of them with SQL operations where applicable.

Let us beging by importing the necessary libraries.

In [1]:
# Importing pandas, numpy (math library), matplotlib, and seaborn
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## How to Create a DataFrame?
A DataFrame which is a two-dimensional, size-mutable, and potentially heterogeneous tabular data structure. There are several ways to create a DataFrame in pandas. Here are the most common ones:

* From a dictionary of lists
* From a list of lists
* From CSV or other files

#### Example
Let us explore the above-mentioned ways through examples.

* From a dictionary of lists or arrays

In [2]:
# Creating a DataFrame from a dictionary of lists
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'City': ['New York', 'Paris', 'Berlin']
}
df = pd.DataFrame(data)
print(df)

      Name  Age      City
0    Alice   25  New York
1      Bob   30     Paris
2  Charlie   35    Berlin

* From a list of lists

In [3]:
# Creating a DataFrame from a list of lists
data = [
    ['Alice', 25, 'New York'],
    ['Bob', 30, 'Paris'],
    ['Charlie', 35, 'Berlin']
]
df = pd.DataFrame(data, columns=['Name', 'Age', 'City'])
print(df)

      Name  Age      City
0    Alice   25  New York
1      Bob   30     Paris
2  Charlie   35    Berlin

* From CSV or other files:
  * .csv or .xlsx files
  * Urls where the dataset is residing

In [4]:
# Read data for car prices
url = (
    "https://raw.githubusercontent.com/juliandnl/redi_ss20/master/cars.csv"
 )
df = pd.read_csv(url)
df.head()

,Make,Model,Year,Variant,Kms,Price,Doors,Kind,Location
0,Volkswagen,Vento,2012,2.5 Luxury 170cv,99950,360000,4.0,Sedán,Córdoba
1,Ford,Ranger,2012,2.3 Cd Xl Plus 4x2,140000,320000,2.0,Pick-Up,Entre Ríos
2,Volkswagen,Fox,2011,1.6 Trendline,132000,209980,5.0,Hatchback,Bs.as. G.b.a. Sur
3,Ford,Ranger,2017,3.2 Cd Xls Tdci 200cv Automática,13000,798000,4.0,Pick-Up,Neuquén
4,Volkswagen,Gol,2013,1.4 Power 83cv 3 p,107000,146000,3.0,Hatchback,Córdoba

#### Exercise 1
Create a dataframe using the data given in the following table. Use both methods, i.e., dictionary of lists and list of lists.

id | age | contract_type | insurance_company | income_level
:-: | :- | :- | :- | :-
1248 | 33 | permanent | aok | 5
1271 | 41 | part-time | tk | 8
1232 | 23 | student | dak | 2

In [16]:
# Your code
# Creating a DataFrame from a dictionary of lists
data = {
    'id': ['1248', 'Bob', 'Charlie'],
    'age': [25, 30, 35],
    'contract_type': ['New York', 'Paris', 'Berlin']
    }
pd.DataFrame(data)
print(data)

{'id': ['1248', 'Bob', 'Charlie'], 'age': [25, 30, 35], 'contract_type': ['New York', 'Paris', 'Berlin']}

## Pandas vs SQL

Pandas and SQL both are commonly used for handling and querying data. While SQL is a database language to work with relational databases, Pandas is a Python library that allows you to work with data in DataFrames, which are like in-memory tables.

Operation | SQL | Pandas
:-: | :-: | :-:
Select columns | `SELECT column_name FROM table_name` | `df['column_name']`
Filter rows	 | `SELECT * FROM table WHERE condition` | `df[df['column_name'] == condition]`
Aggregate functions | `GROUP BY` |  `df.groupby(['column']).agg()`
Join tables | `JOIN` |  `pd.merge(df1, df2, on='column')`

### Example

Let's load a sample dataset and explore the differences between SQL and Pandas for basic operations like selecting and filtering data.

**BUT** to run SQL commands in python, we need to use a special library *pandasql*.

In [17]:
!pip install pandasql

from pandasql import sqldf

Collecting pandasql
  Downloading pandasql-0.7.3.tar.gz (26 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (from pandasql) (2.0.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (from pandasql) (2.2.2)
Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.11/dist-packages (from pandasql) (2.0.40)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas->pandasql) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas->pandasql) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas->pandasql) (2025.2)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.11/dist-packages (from sqlalchemy->pandasql) (3.1.1)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.11/dist-packages (from sqlalchemy->pandasql) (4.13.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas->pandasql) (1.17.0)
Building wheels for collected packages: pandasql
  Building wheel for pandasql (setup.py) ... done
  Created wheel for pandasql: filename=pandasql-0.7.3-py3-none-any.whl size=26773 sha256=36478ac52585521f0459edc326a0e373f0d88aa9cc2dd9624ace53c2e8366542
  Stored in directory: /root/.cache/pip/wheels/68/5d/a5/edc271b998f909801d7956959f699b976cc9896075dc47c153
Successfully built pandasql
Installing collected packages: pandasql
Successfully installed pandasql-0.7.3

We can now run an SQL query as follows:

In [18]:
query = """
    SELECT *
    FROM cars
    Limit 5
"""

# Execute SQL query on DataFrame
result = sqldf(query)
print(result)

PandaSQLException: (sqlite3.OperationalError) no such table: cars
[SQL:
    SELECT *
    FROM cars
    Limit 5
]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

### Exercise 2
Create queries using the table above.

In [ ]:
# Filter rows where Make=Volkswagon
query = # your code
result = sqldf(query)
print(result)

# Groupby based on the Make column
query = # your code
result = sqldf(query)
print(result)

## Explore data

There are several pandas methods that can be used to explore data. These are:

* `df.head()`: Displays the first 5 rows of the DataFrame.
* `df.tail()`: Displays the last 5 rows.
* `df.info()`: Provides a concise summary of the DataFrame (including data types).
* `df.describe()`: Generates descriptive statistics for numeric columns.

#### Exercise 3
Apply the above-mentioned methods to the dataset loaded above. Explore the difference between them.

In [19]:
# Your code
df.head(10)

,Make,Model,Year,Variant,Kms,Price,Doors,Kind,Location
0,Volkswagen,Vento,2012,2.5 Luxury 170cv,99950,360000,4.0,Sedán,Córdoba
1,Ford,Ranger,2012,2.3 Cd Xl Plus 4x2,140000,320000,2.0,Pick-Up,Entre Ríos
2,Volkswagen,Fox,2011,1.6 Trendline,132000,209980,5.0,Hatchback,Bs.as. G.b.a. Sur
3,Ford,Ranger,2017,3.2 Cd Xls Tdci 200cv Automática,13000,798000,4.0,Pick-Up,Neuquén
4,Volkswagen,Gol,2013,1.4 Power 83cv 3 p,107000,146000,3.0,Hatchback,Córdoba
5,Volkswagen,Amarok,2014,2.0 Cd Tdi 180cv 4x4 Highline C34,115000,790000,4.0,Pick-Up,Buenos Aires Interior
6,Ford,Ka,2012,1.0 Fly Viral 63cv,95243,142000,3.0,Hatchback,Bs.as. G.b.a. Sur
7,Ford,Ka,2012,1.6 Fly Viral 95cv,110000,148000,3.0,Hatchback,Buenos Aires Interior
8,Ford,Focus III,2017,1.6 S,17500,367000,5.0,Hatchback,Buenos Aires Interior
9,Ford,Fiesta Kinetic Design,2014,1.6 Sedan Titanium Powershift 120cv,43000,287000,4.0,Sedán,Bs.as. G.b.a. Norte

In [20]:
df.tail()

,Make,Model,Year,Variant,Kms,Price,Doors,Kind,Location
9995,Ford,Focus III,2016,2.0 Se,67000,399000,5.0,Hatchback,Bs.as. G.b.a. Oeste
9996,Volkswagen,Bora,2012,1.9 Trendline I 100cv,120000,240000,4.0,Sedán,Buenos Aires Interior
9997,Ford,Fiesta Kinetic Design,2012,1.6 Design 120cv Titanium,89000,250000,5.0,Hatchback,Tucumán
9998,Ford,Fiesta Kinetic Design,2013,1.6 Design 120cv Titanium,76000,295000,5.0,Hatchback,Buenos Aires Interior
9999,Ford,Focus III,2014,2.0 Titanium At6,32000,380000,5.0,Hatchback,Bs.as. G.b.a. Sur

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Make      10000 non-null  object
 1   Model     10000 non-null  object
 2   Year      10000 non-null  int64
 3   Variant   10000 non-null  object
 4   Kms       10000 non-null  int64
 5   Price     10000 non-null  int64
 6   Doors     10000 non-null  float64
 7   Kind      10000 non-null  object
 8   Location  10000 non-null  object
dtypes: float64(1), int64(3), object(5)
memory usage: 703.3+ KB

In [22]:
df.describe()

               Year            Kms         Price         Doors
count  10000.000000   10000.000000  1.000000e+04  10000.000000
mean    2013.293800   74483.338400  3.495455e+05      4.295800
std        1.816043   35150.279998  1.773396e+05      0.889821
min     2011.000000    5094.000000  6.300000e+03      2.000000
25%     2012.000000   49500.000000  2.290000e+05      4.000000
50%     2013.000000   73000.000000  3.000000e+05      5.000000
75%     2015.000000   97000.000000  4.300000e+05      5.000000
max     2018.000000  218000.000000  2.800000e+06      5.000000

In [23]:
df[df.duplicated()]

,Make,Model,Year,Variant,Kms,Price,Doors,Kind,Location
213,Ford,Fiesta Kinetic Design,2012,1.6 Design Sedan 120cv Trend,125000,235000,4.0,Sedán,Bs.as. G.b.a. Norte
435,Volkswagen,Gol,2012,1.4 Power Ps+ac 83cv,108000,145000,5.0,Hatchback,Bs.as. G.b.a. Oeste
866,Volkswagen,Gol Trend,2013,1.6 Pack Iii 101cv I-motion,40000,225000,5.0,Hatchback,Bs.as. G.b.a. Oeste
1112,Ford,Ka,2013,1.6 Pulse Top 95cv,70000,180000,3.0,Hatchback,Bs.as. G.b.a. Sur
1363,Volkswagen,Saveiro,2016,1.6 Gp Cd 101cv Pack High,50000,360000,2.0,Pick-Up,Córdoba
...,...,...,...,...,...,...,...,...,...
9909,Ford,Focus III,2014,2.0 Sedan Se,30000,370000,4.0,Sedán,Neuquén
9916,Volkswagen,Golf,2015,1.4 Comfortline Tsi,43000,420000,5.0,Hatchback,Capital Federal
9932,Ford,Ecosport,2013,2.0 Titanium 143cv 4x2,62000,345000,5.0,SUV,Bs.as. G.b.a. Oeste
9936,Ford,Ecosport,2015,2.0 Titanium 143cv 4x2,43000,435000,5.0,SUV,Bs.as. G.b.a. Oeste
9971,Volkswagen,Voyage,2011,1.6 Comfortline 101cv,140000,175000,4.0,Sedán,Santa Fe

In [25]:
df[df.duplicated(keep=False)]

,Make,Model,Year,Variant,Kms,Price,Doors,Kind,Location
39,Ford,Focus III,2013,2.0 Sedan Titanium Mt,85000,440000,4.0,Sedán,Capital Federal
71,Ford,Ecosport,2017,1.6 Titanium 110cv 4x2,19500,565000,5.0,SUV,Buenos Aires Interior
77,Ford,Fiesta Kinetic Design,2012,1.6 Design Sedan 120cv Trend,125000,235000,4.0,Sedán,Bs.as. G.b.a. Norte
119,Ford,Ecosport,2013,1.6 Se 110cv 4x2,50500,350000,5.0,SUV,Capital Federal
151,Volkswagen,Gol,2012,1.4 Power Ps+ac 83cv,108000,145000,5.0,Hatchback,Bs.as. G.b.a. Oeste
...,...,...,...,...,...,...,...,...,...
9909,Ford,Focus III,2014,2.0 Sedan Se,30000,370000,4.0,Sedán,Neuquén
9916,Volkswagen,Golf,2015,1.4 Comfortline Tsi,43000,420000,5.0,Hatchback,Capital Federal
9932,Ford,Ecosport,2013,2.0 Titanium 143cv 4x2,62000,345000,5.0,SUV,Bs.as. G.b.a. Oeste
9936,Ford,Ecosport,2015,2.0 Titanium 143cv 4x2,43000,435000,5.0,SUV,Bs.as. G.b.a. Oeste
9971,Volkswagen,Voyage,2011,1.6 Comfortline 101cv,140000,175000,4.0,Sedán,Santa Fe

In [24]:
df2=df.drop_duplicates()
df2.duplicated().sum()
df2.describe()

              Year            Kms         Price        Doors
count  9751.000000    9751.000000  9.751000e+03  9751.000000
mean   2013.297713   74394.079479  3.492546e+05     4.298533
std       1.816978   35178.996460  1.768928e+05     0.888443
min    2011.000000    5094.000000  6.300000e+03     2.000000
25%    2012.000000   49000.000000  2.292000e+05     4.000000
50%    2013.000000   73000.000000  3.000000e+05     5.000000
75%    2015.000000   97000.000000  4.300000e+05     5.000000
max    2018.000000  218000.000000  2.800000e+06     5.000000

In [26]:
df2.shape

(9751, 9)

## Selecting Columns

In Pandas, you can select a column (or multiple columns) using the following methods:

* Single column: `df['column_name']`
* Multiple columns: `df[['col1', 'col2']]`

#### Exercise 4
Perform the following tasks:
* Select the column `Make`
* Select the columns `Make` and `Model`
* Select the columns `Make` and `Model` using a SQL query.

In [ ]:
# Your code
df2['Make']

In [ ]:
df2[["Make","Model"]]

In [ ]:
df2['Make'].value_counts(dropna=False)

In [ ]:
df['Make'].value_counts(dropna=False)

In [ ]:
df.head()

**Question**: What is the difference between `df['column_name']` and `df[['column_name']]`? Try it below.

In [ ]:
# Your code
df2[['Make']]

In [ ]:
df2['Make']

In [ ]:
filtered_df = df[(df['Make'] == 'Volkswagen') & (df['Model'] == 'Vento')]

In [ ]:
filtered_df

In [ ]:
df3[(df3['Make']=="Volkswagen") ]

## Filtering
Filtering allows you to retrieve rows that match a particular condition.

- Example: `df[df['column_name'] == condition]`
- Use comparison operators like `>`, `<`, `>=`, `<=`, `!=`.

#### Example
Let us filter out the rows where the column `Make` is equal *Ford*.

In [ ]:
# Your code

#### Exercise 5
Filter out the rows where at least one of the following conditions are met:
* The `Make` is *Volkswagon* and the model is *Vento*
* The `Make` is *Ford* and the model is *Ranger*

In [ ]:
condition_1 = # Your code
condition_2 = # Your code
filtered_df = # Your code

Write the equivalent SQL query.

In [ ]:
query = # your code
result = sqldf(query)
print(result)

## Group by
`groupby()` is used to split data into groups based on a particular column and then apply aggregate functions, e.g., `sum()`, `mean()`.

SQL equivalent of this method is `GROUP BY` clause.

#### Example
We would like to find out the average price for different car companies. Let us find that out using `groupby()` and `mean()` methods.

In [ ]:
groupby_col = # Your code
df.groupby(groupby_col)["Price"].mean()

**Question**: Is there any other way to do it?

**Hint**: Think of using the `agg()` method.

<!--
# Copyright © 2024 Meysam Goodarzi
This notebook is licensed under CC BY-NC 4.0 with the following amandments:
- Individuals may use, share, and adapt this material for non-commercial purposes with attribution.
- Institutions/Companies must obtain written consent to use this material, except for nonprofits.
- Commercial use is prohibited without permission.  
Contact: analytica@meysam-goodarzi.com.
-->

In [ ]:
groupby_col = "Make"
# Your code

How would you do it with an SQL query?

In [ ]:
query = # your code
result = sqldf(query)
print(result)

## Accessing
We can use the following methods to access the content of the dataframes.

* `loc[]`: Selects rows and columns based on **labels**.
* `iloc[]`: Selects rows and columns based on **index** position.
* `query()`: Filters rows using a SQL-like expression.

#### Example
Explore the above-mentioned methods on the dataset. Try multiple configs and see the results.

In [27]:
df.loc[0]
# df.iloc[0]

Make              Volkswagen
Model                  Vento
Year                    2012
Variant     2.5 Luxury 170cv
Kms                    99950
Price                 360000
Doors                    4.0
Kind                   Sedán
Location             Córdoba
Name: 0, dtype: object

#### Exercise 6
Use all the above-mentioned methods to access the rows where:
* The car is Volswagon and the year of production is after 2014

In [ ]:
# loc[]
condition_1 = (df['Make'] == 'Volkswagen')
condition_2 = # Your code
df.loc[condition_1 & condition_2]

# iloc[]
condition_1 = # Your code
condition_2 = # Your code
df.iloc[condition_1 & condition_2]


# SQL query
query = # Your code
df.query(query).head(5)

## Sorting
You can sort data using
* `sort_values()`: Sorting a dataframe based on the values of a column/columns
* `sort_index()`: Sorting a dataframe based on the indices of the rows

SQL equivalent of this command is `ORDER BY` clause.

#### Exercise 7
Sort the dataframe based on the year of the productions in a descening order.

In [ ]:
# Your code

## Aggregate Methods

Pandas supports common aggregation methods:

* `sum()`: Sum of values.
* `mean()`: Average of values.
* `median()`: Median of values.
* `count()`: Count non-NA values.
* `max()`, `min()`: Maximum and minimum values.
* `unique()`: Return unique values.

#### Example
Let us apply the numerical ones on the *Price* column.

In [ ]:
# Calculate sum, mean, median, min, and max of Prices

**Question**: Is there any other way to do it?

**Hint**: Explore the possibilities using the `agg()` method.

In [ ]:
# Your code

#### Exercise 8
Count the number of cars from each company and explore how many unique models each company has in the dataset.

In [ ]:
# Your code

**Congratulations! You have finished the Notebook! Great Job!**
🤗🙌👍👏💪
<!--
# Copyright © 2024 Meysam Goodarzi
This notebook is licensed under CC BY-NC 4.0 with the following amandments:
- Individuals may use, share, and adapt this material for non-commercial purposes with attribution.
- Institutions/Companies must obtain written consent to use this material, except for nonprofits.
- Commercial use is prohibited without permission.  
Contact: analytica@meysam-goodarzi.com.
-->