In [1]:
import pandas as pd

In [4]:
df = pd.read_csv('../Data/co-emissions_pc.csv')
df[:3]

        Entity  Year  Annual CO₂ emissions (per capita)
0  Afghanistan  1949                           0.001992
1  Afghanistan  1950                           0.010837
2  Afghanistan  1951                           0.011625

In [5]:
df.columns = ['Country', 'Year', 'annual CO2 emission pc. (in tonnes)']
df[:3]

       Country  Year  annual CO2 emission pc. (in tonnes)
0  Afghanistan  1949                             0.001992
1  Afghanistan  1950                             0.010837
2  Afghanistan  1951                             0.011625

In [6]:
df.to_csv('../Data/co2_emission_pc_cleaned.csv', index=False)