In [1]:
import pandas as pd

df = pd.read_csv('../Data/HALE.csv')

In [2]:
df.head(3)

,Unnamed: 0,Healthy life expectancy (HALE) at birth (years),Healthy life expectancy (HALE) at birth (years).1,Healthy life expectancy (HALE) at birth (years).2,Healthy life expectancy (HALE) at birth (years).3,Healthy life expectancy (HALE) at birth (years).4,Healthy life expectancy (HALE) at birth (years).5,Healthy life expectancy (HALE) at birth (years).6,Healthy life expectancy (HALE) at birth (years).7,Healthy life expectancy (HALE) at birth (years).8,...,Healthy life expectancy (HALE) at age 60 (years).2,Healthy life expectancy (HALE) at age 60 (years).3,Healthy life expectancy (HALE) at age 60 (years).4,Healthy life expectancy (HALE) at age 60 (years).5,Healthy life expectancy (HALE) at age 60 (years).6,Healthy life expectancy (HALE) at age 60 (years).7,Healthy life expectancy (HALE) at age 60 (years).8,Healthy life expectancy (HALE) at age 60 (years).9,Healthy life expectancy (HALE) at age 60 (years).10,Healthy life expectancy (HALE) at age 60 (years).11
0,NaN,Both sexes,Both sexes,Both sexes,Both sexes,Male,Male,Male,Male,Female,...,Both sexes,Both sexes,Male,Male,Male,Male,Female,Female,Female,Female
1,"Countries, territories and areas",2019,2015,2010,2000,2019,2015,2010,2000,2019,...,2010,2000,2019,2015,2010,2000,2019,2015,2010,2000
2,Afghanistan,53.9,52.6,51.1,46.8,54.7,52.8,51.5,46.9,53.2,...,10.9,10.2,11.2,11.5,11.1,10.2,10.6,10.9,10.7,10.1

In [4]:
cols_to_keep = ['Unnamed: 0'] + df.columns[df.iloc[0] == 'Both sexes'].tolist()
df_both = df[cols_to_keep]
df_both[:3]

,Unnamed: 0,Healthy life expectancy (HALE) at birth (years),Healthy life expectancy (HALE) at birth (years).1,Healthy life expectancy (HALE) at birth (years).2,Healthy life expectancy (HALE) at birth (years).3,Healthy life expectancy (HALE) at age 60 (years),Healthy life expectancy (HALE) at age 60 (years).1,Healthy life expectancy (HALE) at age 60 (years).2,Healthy life expectancy (HALE) at age 60 (years).3
0,NaN,Both sexes,Both sexes,Both sexes,Both sexes,Both sexes,Both sexes,Both sexes,Both sexes
1,"Countries, territories and areas",2019,2015,2010,2000,2019,2015,2010,2000
2,Afghanistan,53.9,52.6,51.1,46.8,10.8,11.2,10.9,10.2

In [16]:
df_both.drop(df_both.index[0])

,Unnamed: 0,Healthy life expectancy (HALE) at birth (years),Healthy life expectancy (HALE) at birth (years).1,Healthy life expectancy (HALE) at birth (years).2,Healthy life expectancy (HALE) at birth (years).3,Healthy life expectancy (HALE) at age 60 (years),Healthy life expectancy (HALE) at age 60 (years).1,Healthy life expectancy (HALE) at age 60 (years).2,Healthy life expectancy (HALE) at age 60 (years).3
1,"Countries, territories and areas",2019,2015,2010,2000,2019,2015,2010,2000
2,Afghanistan,53.9,52.6,51.1,46.8,10.8,11.2,10.9,10.2
3,Albania,69.1,69.0,67.6,65.2,16.6,16.7,16.7,15.0
4,Algeria,66.4,66.0,65.5,62.7,16.0,15.9,15.6,14.6
5,Angola,54.8,53.7,50.6,42.9,12.6,12.4,11.9,10.7
...,...,...,...,...,...,...,...,...,...
180,Venezuela (Bolivarian Republic of),64.4,65.1,65.3,64.7,16.3,16.4,16.5,16.0
181,Viet Nam,65.3,64.9,64.5,63.3,14.8,14.7,14.5,14.3
182,Yemen,57.5,58.4,58.6,54.5,13.3,13.5,13.3,12.6
183,Zambia,54.4,52.7,49.4,39.0,12.6,12.3,11.7,10.0
184,Zimbabwe,53.1,51.2,45.2,41.0,11.5,11.2,10.5,10.6

In [34]:
filtered_cols = ['Unnamed: 0'] + [
    col
    for col in df_drop.columns
    if col.startswith('Healthy life expectancy (HALE) at birth')
]

df_birth = df_drop[filtered_cols]
df_birth[:3]

,Unnamed: 0,Healthy life expectancy (HALE) at birth (years),Healthy life expectancy (HALE) at birth (years).1,Healthy life expectancy (HALE) at birth (years).2,Healthy life expectancy (HALE) at birth (years).3
1,"Countries, territories and areas",2019,2015,2010,2000
2,Afghanistan,53.9,52.6,51.1,46.8
3,Albania,69.1,69.0,67.6,65.2

In [38]:
# df_head = df_birth.copy()
# df_head.columns = df_birth.iloc[0]
df_head = df_head.drop(df_head.index[0])
df_head.columns = ['Country'] + df_head.columns[1:].tolist()
df_head = df_head.reset_index(drop=True)
df_head[:3]

       Country  2019  2015  2010  2000
0  Afghanistan  53.9  52.6  51.1  46.8
1      Albania  69.1  69.0  67.6  65.2
2      Algeria  66.4  66.0  65.5  62.7

In [42]:
df_birth_long = (
    df_head.melt(id_vars=['Country'], var_name='Year', value_name='HALE (at birth)')
    .sort_values(['Country', 'Year'])
    .reset_index(drop=True)
)

In [43]:
df_birth_long[:3]

       Country  Year HALE (at birth)
0  Afghanistan  2000            46.8
1  Afghanistan  2010            51.1
2  Afghanistan  2015            52.6

In [44]:
filtered_cols2 = ['Unnamed: 0'] + [
    col
    for col in df_drop.columns
    if col.startswith('Healthy life expectancy (HALE) at age 60')
]

df_60 = df_drop[filtered_cols2]
df_60[:3]

,Unnamed: 0,Healthy life expectancy (HALE) at age 60 (years),Healthy life expectancy (HALE) at age 60 (years).1,Healthy life expectancy (HALE) at age 60 (years).2,Healthy life expectancy (HALE) at age 60 (years).3
1,"Countries, territories and areas",2019,2015,2010,2000
2,Afghanistan,10.8,11.2,10.9,10.2
3,Albania,16.6,16.7,16.7,15.0

In [45]:
df_60_head = df_60.copy()
df_60_head.columns = df_60.iloc[0]
df_60_head = df_60_head.drop(df_60_head.index[0])
df_60_head.columns = ['Country'] + df_60_head.columns[1:].tolist()
df_60_head = df_60_head.reset_index(drop=True)
df_60_head[:3]

       Country  2019  2015  2010  2000
0  Afghanistan  10.8  11.2  10.9  10.2
1      Albania  16.6  16.7  16.7  15.0
2      Algeria  16.0  15.9  15.6  14.6

In [46]:
df_60_long = (
    df_60_head.melt(id_vars=['Country'], var_name='Year', value_name='HALE (at 60)')
    .sort_values(['Country', 'Year'])
    .reset_index(drop=True)
)

df_60_long[:3]

       Country  Year HALE (at 60)
0  Afghanistan  2000         10.2
1  Afghanistan  2010         10.9
2  Afghanistan  2015         11.2

In [47]:
df_birth_long[:3]

       Country  Year HALE (at birth)
0  Afghanistan  2000            46.8
1  Afghanistan  2010            51.1
2  Afghanistan  2015            52.6

In [50]:
df_merge = df_60_long.merge(df_birth_long, how='outer', on=['Country', 'Year'])
df_merge[:3]

       Country  Year HALE (at 60) HALE (at birth)
0  Afghanistan  2000         10.2            46.8
1  Afghanistan  2010         10.9            51.1
2  Afghanistan  2015         11.2            52.6

In [51]:
new_order = ['Country', 'Year', 'HALE (at birth)', 'HALE (at 60)']
df_merge = df_merge[new_order]
df_merge[:3]

       Country  Year HALE (at birth) HALE (at 60)
0  Afghanistan  2000            46.8         10.2
1  Afghanistan  2010            51.1         10.9
2  Afghanistan  2015            52.6         11.2

In [52]:
df_merge.isna().sum()

Country            0
Year               0
HALE (at birth)    0
HALE (at 60)       0
dtype: int64

In [53]:
df_merge.to_csv('../Data/HALE_clean.csv', index=False)

In [54]:
pd.read_csv('../Data/HALE_clean.csv')[:3]

       Country  Year  HALE (at birth)  HALE (at 60)
0  Afghanistan  2000             46.8          10.2
1  Afghanistan  2010             51.1          10.9
2  Afghanistan  2015             52.6          11.2