In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('../Data/human_development_index.csv', encoding='latin-1')

df[:3]

,iso3,country,hdicode,region,hdi_rank_2022,hdi_1990,hdi_1991,hdi_1992,hdi_1993,hdi_1994,...,pop_total_2013,pop_total_2014,pop_total_2015,pop_total_2016,pop_total_2017,pop_total_2018,pop_total_2019,pop_total_2020,pop_total_2021,pop_total_2022
0,AFG,Afghanistan,Low,SA,182.0,0.284,0.292,0.299,0.307,0.300,...,31.541208,32.716210,33.753499,34.636207,35.643417,36.686784,37.769498,38.972231,40.099462,41.128771
1,ALB,Albania,High,ECA,74.0,0.649,0.632,0.616,0.618,0.623,...,2.887014,2.884102,2.882480,2.881063,2.879355,2.877013,2.873883,2.866849,2.854710,2.842321
2,DZA,Algeria,High,AS,93.0,0.593,0.596,0.601,0.602,0.603,...,38.000627,38.760168,39.543154,40.339329,41.136546,41.927007,42.705368,43.451666,44.177968,44.903225

In [3]:
df_hdi = df.melt(
    id_vars=['iso3', 'country', 'hdicode', 'region', 'hdi_rank_2022'],
    value_vars=[col for col in df.columns if col.startswith('hdi_')],
    var_name='year',
    value_name='hdi',
)
df_hdi[:2]

  iso3      country hdicode region  hdi_rank_2022      year    hdi
0  AFG  Afghanistan     Low     SA          182.0  hdi_1990  0.284
1  ALB      Albania    High    ECA           74.0  hdi_1990  0.649

In [4]:
df_hdi['year'] = df_hdi['year'].str.replace('hdi_', '')
df_hdi[:2]

  iso3      country hdicode region  hdi_rank_2022  year    hdi
0  AFG  Afghanistan     Low     SA          182.0  1990  0.284
1  ALB      Albania    High    ECA           74.0  1990  0.649

In [5]:
df_pop = df.melt(
    id_vars=['iso3', 'country', 'hdicode', 'region', 'hdi_rank_2022'],
    value_vars=[col for col in df.columns if col.startswith('pop_total_')],
    var_name='year',
    value_name='pop_total',
)

df_pop[:3]

  iso3      country hdicode region  hdi_rank_2022            year  pop_total
0  AFG  Afghanistan     Low     SA          182.0  pop_total_1990  10.694796
1  ALB      Albania    High    ECA           74.0  pop_total_1990   3.295066
2  DZA      Algeria    High     AS           93.0  pop_total_1990  25.518074

In [6]:
df_pop['year'] = df_pop['year'].str.replace('pop_total_', '')
df_pop[:3]

  iso3      country hdicode region  hdi_rank_2022  year  pop_total
0  AFG  Afghanistan     Low     SA          182.0  1990  10.694796
1  ALB      Albania    High    ECA           74.0  1990   3.295066
2  DZA      Algeria    High     AS           93.0  1990  25.518074

In [7]:
df_merge = df_hdi.merge(
    df_pop,
    how='left',
    on=['iso3', 'country', 'hdicode', 'region', 'hdi_rank_2022', 'year'],
)
df_merge[:3]

  iso3      country hdicode region  hdi_rank_2022  year    hdi  pop_total
0  AFG  Afghanistan     Low     SA          182.0  1990  0.284  10.694796
1  ALB      Albania    High    ECA           74.0  1990  0.649   3.295066
2  DZA      Algeria    High     AS           93.0  1990  0.593  25.518074

In [8]:
df_merge.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20394 entries, 0 to 20393
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   iso3           20394 non-null  object
 1   country        20394 non-null  object
 2   hdicode        19107 non-null  object
 3   region         14949 non-null  object
 4   hdi_rank_2022  19107 non-null  float64
 5   year           20394 non-null  object
 6   hdi            16199 non-null  float64
 7   pop_total      6798 non-null   float64
dtypes: float64(3), object(5)
memory usage: 1.2+ MB

In [9]:
df_merge.isnull().sum()

iso3                 0
country              0
hdicode           1287
region            5445
hdi_rank_2022     1287
year                 0
hdi               4195
pop_total        13596
dtype: int64

In [10]:
df_merge[df_merge.hdi.isnull()][2000:]

,iso3,country,hdicode,region,hdi_rank_2022,year,hdi,pop_total
9997,MHL,Marshall Islands,High,EAP,102.0,f_2005,NaN,NaN
10001,FSM,Micronesia (Federated States of),Medium,EAP,135.0,f_2005,NaN,NaN
10003,MCO,Monaco,NaN,NaN,NaN,f_2005,NaN,NaN
10008,MMR,Myanmar,Medium,EAP,144.0,f_2005,NaN,NaN
10034,KNA,Saint Kitts and Nevis,Very High,LAC,51.0,f_2005,NaN,NaN
...,...,...,...,...,...,...,...,...
20334,KNA,Saint Kitts and Nevis,Very High,LAC,51.0,m_2022,NaN,NaN
20336,VCT,Saint Vincent and the Grenadines,High,LAC,81.0,m_2022,NaN,NaN
20339,STP,Sao Tome and Principe,Medium,SSA,141.0,m_2022,NaN,NaN
20351,SSD,South Sudan,Low,SSA,192.0,m_2022,NaN,NaN
20368,TKM,Turkmenistan,High,ECA,94.0,m_2022,NaN,NaN

In [11]:
df_merge.year.str.count('') == 4

0        False
1        False
2        False
3        False
4        False
         ...
20389    False
20390    False
20391    False
20392    False
20393    False
Name: year, Length: 20394, dtype: bool

In [12]:
df_merge[df_merge.year.str.isdigit()].isnull().sum()

iso3                0
country             0
hdicode           429
region           1815
hdi_rank_2022     429
year                0
hdi               627
pop_total           0
dtype: int64

In [13]:
df_filtered = df_merge[df_merge.year.str.isdigit()]
df_filtered[:5]

  iso3      country    hdicode region  hdi_rank_2022  year    hdi  pop_total
0  AFG  Afghanistan        Low     SA          182.0  1990  0.284  10.694796
1  ALB      Albania       High    ECA           74.0  1990  0.649   3.295066
2  DZA      Algeria       High     AS           93.0  1990  0.593  25.518074
3  AND      Andorra  Very High    NaN           35.0  1990    NaN   0.053569
4  AGO       Angola     Medium    SSA          150.0  1990    NaN  11.828637

In [14]:
# df_filtered[df_filtered.hdi_rank_2022.isnull()]
df_filtered[(df_filtered['year'] >= '2000') & (df_filtered['hdi'].isnull())]

,iso3,country,hdicode,region,hdi_rank_2022,year,hdi,pop_total
2065,ATG,Antigua and Barbuda,Very High,LAC,54.0,2000,NaN,0.075055
2079,BTN,Bhutan,Medium,SA,125.0,2000,NaN,0.587207
2114,ERI,Eritrea,Low,SSA,175.0,2000,NaN,2.392879
2127,GRD,Grenada,High,LAC,73.0,2000,NaN,0.107432
2130,GNB,Guinea-Bissau,Low,SSA,179.0,2000,NaN,1.230849
...,...,...,...,...,...,...,...,...
6476,PRK,Korea (Democratic People's Rep. of),NaN,EAP,NaN,2021,NaN,25.971909
6501,MCO,Monaco,NaN,NaN,NaN,2021,NaN,0.036686
6547,SOM,Somalia,Low,AS,193.0,2021,NaN,17.065581
6682,PRK,Korea (Democratic People's Rep. of),NaN,EAP,NaN,2022,NaN,26.069416
6707,MCO,Monaco,NaN,NaN,NaN,2022,NaN,0.036469

In [15]:
df_2000 = df_filtered[df_filtered['year'] >= '2000']
df_2000[:10]

,iso3,country,hdicode,region,hdi_rank_2022,year,hdi,pop_total
2060,AFG,Afghanistan,Low,SA,182.0,2000,0.340,19.542983
2061,ALB,Albania,High,ECA,74.0,2000,0.678,3.182021
2062,DZA,Algeria,High,AS,93.0,2000,0.652,30.774621
2063,AND,Andorra,Very High,NaN,35.0,2000,0.815,0.066098
2064,AGO,Angola,Medium,SSA,150.0,2000,0.380,16.394062
2065,ATG,Antigua and Barbuda,Very High,LAC,54.0,2000,NaN,0.075055
2066,ARG,Argentina,Very High,LAC,48.0,2000,0.780,37.070774
2067,ARM,Armenia,High,ECA,76.0,2000,0.656,3.168524
2068,AUS,Australia,Very High,NaN,10.0,2000,0.896,19.017963
2069,AUT,Austria,Very High,NaN,22.0,2000,0.870,8.010428

In [16]:
df_2000.to_csv('../Data/hdi_from2000_cleaned.csv', index=False)

In [17]:
df_reload = pd.read_csv('../Data/hdi_from2000_cleaned.csv')
df_reload[:5]

  iso3      country    hdicode region  hdi_rank_2022  year    hdi  pop_total
0  AFG  Afghanistan        Low     SA          182.0  2000  0.340  19.542983
1  ALB      Albania       High    ECA           74.0  2000  0.678   3.182021
2  DZA      Algeria       High     AS           93.0  2000  0.652  30.774621
3  AND      Andorra  Very High    NaN           35.0  2000  0.815   0.066098
4  AGO       Angola     Medium    SSA          150.0  2000  0.380  16.394062