In [1]:
import pandas as pd

In [4]:
df = pd.read_csv('../Data/SDGs.csv', encoding='latin-1')
df[:3]

,iso,country,1990,1991,1992,1993,1994,1995,1996,1997,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,AFG,Afghanistan,0.306,0.314,0.322,0.331,0.323,0.343,0.352,0.355,...,0.511,0.517,0.516,0.520,0.522,0.524,0.530,0.525,0.509,0.497
1,ALB,Albania,0.695,0.681,0.663,0.665,0.671,0.681,0.693,0.690,...,0.842,0.837,0.839,0.837,0.841,0.833,0.833,0.807,0.810,0.808
2,DZA,Algeria,0.639,0.642,0.647,0.649,0.650,0.654,0.666,0.674,...,0.779,0.781,0.778,0.759,0.759,0.756,0.758,0.748,0.758,0.758

In [6]:
df_long = df.melt(id_vars=['iso', 'country'], var_name='year', value_name='sdg_index')
df_long[:10]

   iso              country  year  sdg_index
0  AFG          Afghanistan  1990      0.306
1  ALB              Albania  1990      0.695
2  DZA              Algeria  1990      0.639
3  AGO               Angola  1990        NaN
4  ATG  Antigua and Barbuda  1990        NaN
5  ARG            Argentina  1990      0.774
6  ARM              Armenia  1990        NaN
7  AUS            Australia  1990      0.427
8  AUT              Austria  1990      0.648
9  AZE           Azerbaijan  1990        NaN

In [8]:
df_long.isnull().sum()

iso            0
country        0
year           0
sdg_index    317
dtype: int64

In [9]:
df_long[df_long['sdg_index'].isnull()]

      iso              country  year  sdg_index
3     AGO               Angola  1990        NaN
4     ATG  Antigua and Barbuda  1990        NaN
6     ARM              Armenia  1990        NaN
9     AZE           Azerbaijan  1990        NaN
17    BTN               Bhutan  1990        NaN
...   ...                  ...   ...        ...
2612  ATG  Antigua and Barbuda  2006        NaN
2625  BTN               Bhutan  2006        NaN
2788  BTN               Bhutan  2007        NaN
2951  BTN               Bhutan  2008        NaN
3114  BTN               Bhutan  2009        NaN

[317 rows x 4 columns]

In [13]:
df_long[df_long.year >= '2000'].isnull().sum()

iso           0
country       0
year          0
sdg_index    56
dtype: int64

In [14]:
df_2000 = df_long[df_long.year >= '2000']
df_2000[:10]

      iso              country  year  sdg_index
1630  AFG          Afghanistan  2000      0.367
1631  ALB              Albania  2000      0.730
1632  DZA              Algeria  2000      0.702
1633  AGO               Angola  2000      0.410
1634  ATG  Antigua and Barbuda  2000        NaN
1635  ARG            Argentina  2000      0.802
1636  ARM              Armenia  2000      0.706
1637  AUS            Australia  2000      0.306
1638  AUT              Austria  2000      0.527
1639  AZE           Azerbaijan  2000      0.682

In [16]:
df_2000.to_csv('../Data/SDG_from2000_clean.csv', index=False)

In [17]:
df_relaod = pd.read_csv('../Data/SDG_from2000_clean.csv')
df_relaod[:10]

   iso              country  year  sdg_index
0  AFG          Afghanistan  2000      0.367
1  ALB              Albania  2000      0.730
2  DZA              Algeria  2000      0.702
3  AGO               Angola  2000      0.410
4  ATG  Antigua and Barbuda  2000        NaN
5  ARG            Argentina  2000      0.802
6  ARM              Armenia  2000      0.706
7  AUS            Australia  2000      0.306
8  AUT              Austria  2000      0.527
9  AZE           Azerbaijan  2000      0.682